fix(install): pip install git+... failed  due to README codepage
- Error: 
C:\Apps\co2mpas_AIO-v1.6.0.dev4\CO2MPAS>pip install
git+https://github.com/JRCSTU/co2mpas.git@dev
Collecting git+https://github.com/JRCSTU/co2mpas.git@dev
  Cloning https://github.com/JRCSTU/co2mpas.git (to dev) to
c:\users\dimitris\appdata\local\temp\pip-20qh5wxo-build
Username for 'https://github.com':
Password for 'https://dimitriskomnos@github.com':
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File
"C:\Users\dimitris\AppData\Local\Temp\pip-20qh5wxo-build\setup.py", line
112, in <module>
        readme_lines = read_text_lines('README.rst')
      File
"C:\Users\dimitris\AppData\Local\Temp\pip-20qh5wxo-build\setup.py", line
38, in read_text_lines
        return fd.readlines()
      File
"C:\Apps\co2mpas_AIO-v1.6.0.dev4\Apps\WinPython\python-3.6.1.amd64\lib\encodings\cp1253.py",
line 23, in decode
        return
codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in
position 4303: character maps to <undefined>