feat(main): preserve source logger when exit_with_pride
+ FIX 6 baseapp-TCs FAILs (still 3 ERRS) since 119b40303af (FATAL if no
configs) with:
  AssertionError: no logs of level ERROR or higher triggered on
tests.sampling.test_baseapp.MyCmd